parallel-jobs = 1
# patches-version = "dev"
# cli-version = "dev"
enable-module-update = true

[rumble-morphe]
enabled = true 
app-name = "rumble"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "arandomhooman/hoomans-morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://rumble.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/rumble-inc/rumble"
dpi = "nodpi anydpi"

