parallel-jobs = 1
# patches-version = "dev"
# cli-version = "dev"
enable-module-update = true

[instagram-morphe]
enabled = true 
app-name = "instagram"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "brosssh/morphe-patches"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
dpi = "nodpi anydpi"
archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.instagram.android"

[instagram-morphe-piko]
enabled = true 
app-name = "instagram"
rv-brand = "morphe-piko"
build-mode = "both"
arch = "both"
version = "v430.0.0.53.80"
patches-source = "crimera/piko"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/instagram/instagram-instagram"
dpi = "nodpi anydpi"
archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"
github-dlurl = "https://github.com/nullcpy/apks/releases/tag/com.instagram.android"

[youtube-morphe]
enabled = true
app-name = "youtube"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-morphe]
enabled = true
app-name = "youtube-music"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[reddit-morphe]
enabled = true
app-name = "reddit"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
dpi = "nodpi anydpi"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[google-photos-morphe]
enabled = true
app-name = "google-photos"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
dpi = "nodpi anydpi"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[youtube-morphe-exp]
enabled = true
app-name = "youtube"
rv-brand = "morphe-exp"
build-mode = "both"
arch = "both"
version = "latest"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
dpi = "nodpi anydpi"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-morphe-exp]
enabled = true
app-name = "youtube-music"
rv-brand = "morphe-exp"
build-mode = "both"
version = "latest"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
dpi = "nodpi anydpi"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[reddit-morphe-exp]
enabled = true
app-name = "reddit"
rv-brand = "morphe-exp"
build-mode = "both"
arch = "both"
version = "latest"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
dpi = "nodpi anydpi"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"