[youtube-revanced]
enabled = true
app-name = "youtube"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-revanced]
enabled = true
app-name = "youtube-music"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[google-photos-revanced]
enabled = true
app-name = "google-photos"
rv-brand = "revanced"
build-mode = "both"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[messenger-revanced]
enabled = true
app-name = "messenger"
rv-brand = "revanced"
build-mode = "apk"
arch = "both"
patches-source = "ReVanced/revanced-patches"
cli-source = "ReVanced/revanced-cli"
uptodown-dlurl = "https://facebook-messenger.en.uptodown.com/android"
# dpi = "360-480dpi nodpi anydpi"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger"

[youtube-anddea]
enabled = true
app-name = "youtube"
rv-brand = "anddea"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patcher-args = "-e 'Theme' -OdarkThemeBackgroundColor=@android:color/black"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-anddea]
enabled = true
app-name = "youtube-music"
rv-brand = "anddea"
build-mode = "both"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patcher-args = "-e 'Dark theme' -OdarkThemeBackgroundColor=@android:color/black"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[twitter-morphe]
enabled = true 
app-name = "twitter"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "crimera/piko"
# version = "11.81.0-release.0"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# dpi = "120-640dpi 480dpi nodpi anydpi"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.twitter.android"

[youtube-morphe]
enabled = true
app-name = "youtube"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.youtube"

[youtube-music-morphe]
enabled = true
app-name = "youtube-music"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.youtube.music"

[reddit-morphe]
enabled = true
app-name = "reddit"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# dpi = "120-640dpi nodpi anydpi"
# apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[google-photos-morphe]
enabled = true
app-name = "google-photos"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "RookieEnough/De-ReVanced"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[gboard-morphe]
enabled = true
app-name = "gboard"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "jkennethcarino/adobo"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://gboard-go.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.inputmethod.latin"

[instagram-morphe]
enabled = true 
app-name = "instagram"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "brosssh/morphe-patches"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"

[instagram-morphe-piko]
enabled = true 
app-name = "instagram"
rv-brand = "morphe-piko"
build-mode = "apk"
arch = "both"
patches-source = "crimera/piko"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://instagram.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"

[macrodroid-morphe]
enabled = true 
app-name = "macrodroid"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "Paresh-Maheshwari/paresh-patches"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://macrodroid.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.instagram.android"

[truecaller-morphe]
enabled = true
app-name = "truecaller"
rv-brand = "morphe"
build-mode = "both"
arch = "both"
patches-source = "Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://truecaller.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
archive-dlurl = "https://archive.org/download/geologically/apks/com.truecaller"

[fing-morphe]
enabled = true
app-name = "fing"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/photos"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.google.android.apps.photos"

[telegram-morphe-foss]
enabled = true 
app-name = "telegram"
rv-brand = "morphe-foss"
build-mode = "apk"
arch = "both"
patches-source = "Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"

[proton-vpn-morphe]
enabled = true
app-name = "proton-vpn"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-secure-and-free-vpn"
archive-dlurl = "https://archive.org/download/geologically/apks/ch.protonvpn.android"

[reddit-morphe-patcheddit]
enabled = true
app-name = "reddit"
rv-brand = "morphe-patcheddit"
build-mode = "apk"
arch = "both"
patches-source = "wchill/patcheddit"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# dpi = "120-640dpi nodpi anydpi"
# apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"

[autosync-morphe]
enabled = true
app-name = "autosync"
rv-brand = "morphe"
build-mode = "apk"
arch = "both"
patches-source = "BholeyKaBhakt/revanced-patches-xtra"
# patcher-args = "--continue-on-error"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://autosync.en.uptodown.com/android"

[reddit-morphe-adobo]
enabled = true
app-name = "reddit"
rv-brand = "morphe-adobo"
build-mode = "apk"
arch = "both"
patches-source = "jkennethcarino/adobo"
cli-source = "MorpheApp/morphe-cli"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
# dpi = "120-640dpi nodpi anydpi"
# apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.reddit.frontpage"


