name: Cleanup

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # Run on the 1st of every month at 00:00 UTC

concurrency:
  group: clean
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      actions: write
    timeout-minutes: 10
    steps:
      - name: Delete Older Releases and Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: true
          delete_tags: true
          releases_keep_latest: 198
          delete_workflows: true
          workflows_keep_day: 30
          releases_keep_keyword: stable/beta
          gh_token: ${{ secrets.GITHUB_TOKEN }}

  trigger_website_update:
    needs: [ cleanup ]
    if: needs.cleanup.result == 'success'
    uses: ./.github/workflows/update-website.yml
    secrets: inherit
