name: Update Website

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: website
  cancel-in-progress: true

jobs:
  dispatch_update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Dispatch Website Cache Update
        run: |
          curl -X POST https://api.github.com/repos/nullcpy/nullcpy.github.io/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.WEBSITE_DISPATCH_TOKEN }}" \
          -d '{"event_type": "update-catalog-cache"}'
