name: Build

on:
  workflow_call:
  workflow_dispatch:
      
concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 120
    services:
      flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
          - 8191:8191
    steps:
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0
          submodules: true

#      - name: Resolve build context
#        id: context
#       run: bash .github/scripts/build_resolve_context.sh "${{ inputs.config_file }}"

#      - name: Resolve version code
#        id: version
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: bash .github/scripts/build_resolve_version.sh
      
      - name: Extract keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 -d > ks.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d > ks-p12.keystore
      - name: Build modules and apks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          NEXT_VER_CODE: ${{ steps.version.outputs.NEXT_VER_CODE }}
        run: |
          set -euo pipefail
          ./build.sh "configs/x-shim.toml"

      - name: Get output
        id: get_output
        run: bash .github/scripts/build_get_output.sh

#      - name: Update readme
#        run: |
#          python3 update-readme.py ${{ steps.version.outputs.NEXT_VER_CODE }} "$GITHUB_REPOSITORY"

#      - name: Commit updated readme
#        uses: stefanzweifel/git-auto-commit-action@v7
#        with:
#          branch: main
#          skip_checkout: true
#          file_pattern: README.md
#          commit_message: "Update README for Build No. ${{ steps.version.outputs.NEXT_VER_CODE }} [skip ci]"

      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          body: ${{ steps.get_output.outputs.BUILD_LOG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./build/*
          name: X Shim
          tag_name: x-shim
          overwrite_files: true
